### ISSUE TITLE
Monitoring component

### ISSUE THREAD

**Issue by ross-weir** [nautls/ergomatic#13]
This issue is to discuss implementation of the monitoring component required to be able to retrieve and pass on `onBlock` / `onConfirmedUtxo` / etc events to plugins.

Original spec that lists events on plugins: https://gist.github.com/ross-weir/258272ed82332d0b7818c23195ab80e8#plugins

Below is rough pseudo code that I have in mind for how it might work:

```
currentHeight = 0
mempoolDelivery = {} # map of txid -> bool indicating if mempool tx has been passed to plugins
requiredConfirmations = 3
lastBlocks = new Array(requiredConfirmations)

Every `n` seconds
do
    height = getCurrentHeight()
    
    if height > currentHeight
    do
        newBlock = getBlock(height)
        plugins.all.onBlock(newBlock)

        currentHeight = height
        lastBlocks.push(newBlock)
    end

    if lastBlocks.length >= requiredConfirmations
    do
        confirmedBlock = lastBlocks.shift()
        for tx in confirmedBlock.txs
        do
            plugins.all.onConfirmedTx(tx)
        end
    end

    mempool = getMempool()
    for tx in mempool
    do
        if mempoolDelivery[tx.txid] == false
        do
            plugins.all.onUnconfirmedTx(tx)
            mempoolDelivery[tx.txid] = true
        end
    end

    # invalidate mempoolDelivery in some way to remove confirmed or dropped txs?

end
```

- Still deciding on a good way to ensure mempool txns are delivered only once to plugins and cleaned up if they're dropped or included in chain
- In the original spec we had `onConfirmedUtxo` & `onUnconfirmedUtxo` methods for plugins - are these necessary if we have `onConfirmedTx` & `onUnconfirmedTx` since the txns will include the respective utxos?
  - Could we reduce the events down to `OnBlock`, `OnConfirmedBlock`, `onMempoolTx`? Or *should* we?

**Comment by arobsn** [comment]
@ross-weir do you think that ogre can be used to pass messages directly to ergomatic thus avoiding API pooling?

**Comment by ross-weir** [comment]
> I rewrote your pseudo code with some changes I consider important:
> 
> 1. Prioritize mempool dumping over new block checking
> 2. Remove confirmation setup for now, if it's something further needed, it can be added without breaking changes.
> 3. We need to deal with a certain level of uncertainty when checking for a transaction if it was dropped from the mempool as there is a gap between a transaction being removed from mempool and included in a new block. I'm using `undefinedStateCheks` for such check.

Beautiful, way better than what I had :rocket: 

> @ross-weir do you think that ogre can be used to pass messages directly to ergomatic thus avoiding API pooling?

Not right now as chain syncing is incomplete but having it raise events to eliminate polling is 100% something I wanted to do
